
image:
  width: 1200
  height: 900
  bevDim: 200
  fov: 90

front_cam_trans:
  x: 1.3
  y: 0.0
  z: 2.3
  pitch: 0
  roll: 0
  yaw: 0

right_cam_trans:
  x: 1.3
  y: 0.0
  z: 2.3
  pitch: 0
  roll: 0
  yaw: 60

left_cam_trans:
  x: 1.3
  y: 0.0
  z: 2.3
  pitch: 0
  roll: 0
  yaw: -60

back_cam_trans:
  x: -1.3
  y: 0.0
  z: 2.3
  pitch: 0
  roll: 0
  yaw: 180